services:
  analytics-service:
    image: analytics-service:latest
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "4002:4002"
    networks:
      - internal
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  billing-service:
    image: billing-service:latest
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "4004:4004"
    networks:
      - internal
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005

  postgres1:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "6000:5432"
    volumes:
      - ./postgres-data/patient-service-db:/var/lib/postgresql
    networks:
      - internal

  postgres2:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "6001:5432"
    volumes:
      - ./postgres-data/auth-service-db:/var/lib/postgresql
    networks:
      - internal


  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
#    ports:
#      - "4005:4005"  #Passing through API GATEWAY
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: 2yaPtpi2hyrhPWCl3Vw2U3DUd7mpvk37pghSQuhPXNm

networks:
  internal:
    external: true
